---
- include: folders.yml
  when: setup is defined

- include: users.yml
  when: setup is defined

- include: nginx.yml
  become: 'true'
  become_method: 'sudo'
  tags:
    - nginx
  when: setup is defined or nginx is defined

- include: php-fpm.yml
  become: 'true'
  become_method: 'sudo'
  tags:
    - php
  when: env == 'production' and ( setup is defined or php is defined)

- include: update_code.yml
  when: setup is defined or deploy is defined
