---
- name: Create php-fpm pool
  template:
    src=templates/pool.conf.j2
    dest="/etc/php5/fpm/pool.d/{{ short_name }}"

- name: Create upstart script
  template:
    src=templates/php5-fpm.j2
    dest="/etc/init/{{ short_name }}.conf"

- name: Create php5-fpm-checkconf file
  template:
    src=templates/php5-fpm-checkconf.j2
    dest="/usr/lib/php5/php5-fpm-{{ short_name }}-checkconf"
