---
- name: reload nginx
  become: 'true'
  become_method: 'sudo'
  service: name=nginx state=reloaded

- name: start php-fpm pool
  become: 'true'        
  become_method: 'sudo'
  service: name={{short_name}} state=started
